### ISSUE TITLE
Command write_to_file returned: Error: [Errno 2] No such file or directory: '/home/appuser/auto_gpt_workspace/output.txt'

### ISSUE THREAD

**Issue by rihp** [Significant-Gravitas/Auto-GPT-Benchmarks#18]
This happens after one successful run of the eval

sometimes solved by restarting the computer

found on MacOS

**Comment by rihp** [comment]
Potentially has to do with docker volumes

**Comment by hzhWord** [comment]
Thanks for your reply.
