### ISSUE TITLE
I'm Creating .bat files for Windows Users To Keep It Super Simple

### ISSUE THREAD

**Issue by jonathansheets517** [Significant-Gravitas/Auto-GPT-Benchmarks#21]
Even with clear documentation of all the changes that are needed to get this up and running on Windows OS systems... Most Windows users won't be able to.  

I spent most of the day creating a setup.bat file and a run.bat file. Big Picture Goal of combining them once I iron out everything.

My setup.bat file copies the existing .env OPENAI_API for the user to take one step off the user's hands.

I think .bat benchmark dev pathway for Windows users is superior given that the **goal is to have as many people run Evals as possible.** To do so - we would need a keep it simple stupid install and runner for most windows users. 

Current state of my setup .bat file:
- Checks for Windows OS running Python 3.9 and above
- Checks for Windows OS Git in order to clone the needed repos
- Clones Auto-GPT-Benchmarks Repo
- Creates the Virtual Env
X Activates the virtual Env (Fixing it rn atm)
- Installs the requirements within the Venv
![image](https://user-images.githubusercontent.com/38794445/233748064-3ae6768b-0187-4682-a09d-406ac3d6635a.png)

X Passes over requirements that are already installed but aren't on PATH.  
Example:  WARNING: The script openai.exe is installed in 'C:\Users\jonms\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.

-  Clones the Auto-GPT.git wihtin the Venv
X Clones the repo into the wrong folder (lol, i'm fixing it)
- Copies the key from the .env file into the psuedo sub-module AutoGPT repo

![image](https://user-images.githubusercontent.com/38794445/233749540-77a37cc4-5ec5-4420-b756-abf7cd15b48d.png)

This is taking longer than I wanted due to all the install/reinstalls/updates creating a rats nest of pathways and typical windows bs problems on my machine. =( 
I continue on for the homies.

I just wanted to give an update so someone else doesn't try to bang their head against the wall to install Benchmarks like I have.

**Comment by dschonholtz** [comment]
I think a batch file to install and set up quickly is good. 
I tagged you in discord as well, but I got everything running on my windows 10 machine from scratch. 
Installed, python 3.9, docker, upgraded wsl, cloned everything added API keys. So I know what it is like to go from nothing to it all working. It isn't a smooth process but it is doable. 
Let me know if you want to chat about specific problems.

Otherwise, excited to see a batch file
