### ISSUE TITLE
AutoGPT Benchmarks "records.jsonl" Data Not Saved in README Location when ran as-is

### ISSUE THREAD

**Issue by jonathansheets517** [Significant-Gravitas/Auto-GPT-Benchmarks#22]
I powered through running this on windows with the existing README instructions (with alot of edits) but at the end of it...

There's not even a DATA folder created in \Auto-GPT-Benchmarks\auto_gpt_benchmarking\AutoGPTData
There is no records.jsonl created in any of the Auto-GPT folder when ran either. 

And if the README meant to say the json file will be saved in this location...
\Auto-GPT-Benchmarks\auto_gpt_benchmarking\AutoGPTData

There's only the existing ai_settings.yaml file

Obviously I am working on this in conjunction with the install_run_benchmarks.bat file I am creating.

**Comment by dschonholtz** [comment]
#21 Is the linked relevant issue
