### ISSUE TITLE
Optionally enable bash tools and plugins for evals.

### ISSUE THREAD

**Issue by dschonholtz** [Significant-Gravitas/Auto-GPT-Benchmarks#4]
Currently, we can't run bash, git or shell commands in our AutoGPT container. 
This would be to switch the container to Ubuntu so we can!
This likely involves a PR to the core AutoGPT repo, but that's ok.

**Comment by samuelbutler** [comment]
Let me know what you think of this new Dockerfile and if you run into any issues building the container using it. It should be a drop-in replacement. 

#15

**Comment by dschonholtz** [comment]
Per our discussion I am modifying this as the goal is to enable bash. We now also have plugins in the main repo. 
we should at least evaluate that. Although That could be broken out into a new repo
