### ISSUE TITLE
Large language model evaluation model paper and method aggregation

### ISSUE THREAD

**Issue by dschonholtz** [Significant-Gravitas/Auto-GPT-Benchmarks#8]
There are more ways to evaluate LLMs and agents than just with OpenAI evals.
Evals is just the start.
This is going to be a running issue of what methods exist for evaluation. We will spin off separate issues for integrating them into this repository

**Comment by dschonholtz** [comment]
Evaluating Large Language Models Trained on Code: https://arxiv.org/abs/2107.03374
HuggingFace Zero Shot Evaluations: https://huggingface.co/blog/zero-shot-eval-on-the-hub
Evaluating Large Language Models on a Highly-specialized Topic, Radiation Oncology Physics https://arxiv.org/abs/2304.01938

And of course we have OpenAI's evals: https://github.com/openai/evals

**Comment by jonathansheets517** [comment]
[DAWN STANFORD Bench.pdf](https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks/files/11290635/DAWN.STANFORD.Bench.pdf)

**Comment by dschonholtz** [comment]
This leads to a desperate attempt of keeping up with current benchmarking/evaluation research. Some stuff I am hoping to read in the next few days:
- https://arxiv.org/abs/2304.09842 Chameleon  - Using GPT-4 as a task planner in a compositional framework. (Sounds familiar...) 
- https://arxiv.org/pdf/2201.08808.pdf - Conversational Information Seeking - A book about information retrieval that will be published soon. I am hopefully meeting the author soon to discuss an AutoGPT paper.
- https://arxiv.org/pdf/2212.06094.pdf -  LMQL and the prompting structure there
-  https://arxiv.org/pdf/2302.04761.pdf - ToolFormer -  Specifically how they evaluated the model and the prompting structure they used to beat GPT-3 on relevant benchmarks with a model several of orders magnitude smaller
- https://github.com/1rgs/jsonformer - JsonFormer Deterministically generating JSON
- And probably more... But it is a place to start

**Comment by DarylRodrigo** [comment]
- [Unleashing Infinite-Length Input Capacity for Large-scale Language Models with Self-Controlled Memory System](https://arxiv.org/pdf/2304.13343.pdf): Interesting idea for more efficient memory retrieval.
- [LLM+P: Empowering Large Language Models with Optimal Planning Proficiency](https://arxiv.org/pdf/2304.11477.pdf) Interesting ideas around how to make planning more efficient.
- [Emergent autonomous scientific research capabilities of large language models](https://arxiv.org/pdf/2304.05332.pdf): Maybe not to discuss too much, but this is just really cool. Could spark ideas on how it could interact with hardware etc.
