### ISSUE TITLE
Delete everything from the Agent's workspace instead of select files on cleanup

### ISSUE THREAD

**Issue by dschonholtz** [Significant-Gravitas/Auto-GPT-Benchmarks#9]
Currently we just clean up specific files in the workspace on clean up.
We can delete everything in this dir every time.
https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks/blob/master/auto_gpt_benchmarking/AutoGPTAgent.py#L26

**Comment by dschonholtz** [comment]
The problem here is that the agent sometimes discovers historical files it had written in previous runs. It would be better to remove all of the files written to the dir so the agent really has a completely deterministic empty env on start every time.

**Comment by Wladastic** [comment]
I disagree.
I think the bot should be fed with an info to look at what it did before.
I add that kind of instructions to my ai_settings.yaml, to make sure it doesn't keep googling the same stuff over and over again.

My approach is to have the option to choose to have autogpt look at my "old" folder for example.
It keeps finding gold in there and does really cool stuff then.

**Comment by dschonholtz** [comment]
@Wladastic That's awesome. For this project we want to deterministically test the agent so we don't want variables like that effecting what we are measuring for now.
